### ISSUE TITLE
Package.json

### ISSUE THREAD

**Issue by ghost** [peteclodi/angular-custom-range-slider#22]
You don't have a package.json file. This is an issue.

**Comment by peteclodi** [comment]
Is package.json necessary for non-NPM components?

**Comment by ghost** [comment]
Necessary? No. But, it provides more useful data than just what is relied upon by NPM.

**Comment by peteclodi** [comment]
I'll need you to sit down with me to explain what the difference is between package.json and bower.json to make sure that all useful information is provided.
